# Generated by Django 5.1.3 on 2024-11-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_bmiindex_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmiindex',
            name='name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
