# Generated by Django 5.1.3 on 2024-11-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_bmiindex_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmiindex',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bmiindex',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
