# Generated by Django 5.1.3 on 2024-11-23 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='sent',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='message',
            field=models.TextField(default='No message'),
        ),
    ]
