# Generated by Django 5.1.3 on 2024-11-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinelist',
            name='name',
            field=models.CharField(default='Required', max_length=10),
        ),
    ]
