# Generated by Django 5.1.3 on 2024-11-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_medicinelist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinelist',
            name='image',
            field=models.ImageField(default='', upload_to='products/image'),
        ),
    ]
