# Generated by Django 5.1.3 on 2024-11-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_medicinelist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinelist',
            name='image',
            field=models.ImageField(default='', upload_to='products/image1'),
        ),
    ]
